# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inventory.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'inventory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\x12\tecommerce\"\x91\x01\n\x0fInventoryUpdate\x12\x0b\n\x03sku\x18\x01 \x01(\t\x12\x14\n\x0cwarehouse_id\x18\x02 \x01(\t\x12\x17\n\x0fquantity_change\x18\x03 \x01(\x05\x12\x16\n\x0equantity_after\x18\x04 \x01(\x05\x12\x13\n\x0bupdate_type\x18\x05 \x01(\t\x12\x15\n\rupdated_at_ms\x18\x06 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INVENTORYUPDATE']._serialized_start=31
  _globals['_INVENTORYUPDATE']._serialized_end=176
# @@protoc_insertion_point(module_scope)
