#!/usr/bin/env bash
# Render scripts/queries.sql from live Iceberg table directories under /tmp.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BASE="${TABLEFLOW_ICEBERG_DIR:-/tmp/warpstream-tableflow-iceberg/warpstream/_tableflow}"
OUT="${1:-$ROOT/scripts/queries.sql}"

if [[ ! -d "$BASE" ]]; then
  echo "Missing table dir: $BASE" >&2
  echo "Run configure-tableflow.sh and wait for tables to appear." >&2
  exit 1
fi

CLICKS_TABLE=$(ls -d "$BASE"/ecommerce_kafka__clickstream-* 2>/dev/null | head -n1 || true)
ORDERS_TABLE=$(ls -d "$BASE"/ecommerce_kafka__orders-* 2>/dev/null | head -n1 || true)
INVENTORY_TABLE=$(ls -d "$BASE"/ecommerce_kafka__inventory_updates-* 2>/dev/null | head -n1 || true)

for var_name in CLICKS_TABLE ORDERS_TABLE INVENTORY_TABLE; do
  if [[ -z "${!var_name}" ]]; then
    echo "Could not find $var_name under $BASE" >&2
    ls -la "$BASE" >&2 || true
    exit 1
  fi
done

cat >"$OUT" <<EOF
-- DuckDB queries for the WarpStream Tableflow ecommerce lab.
-- Generated by scripts/render-queries.sh — re-run after tables appear:
--   ./scripts/render-queries.sh
--
-- In the DuckDB CLI: INSTALL iceberg; LOAD iceberg;

-- Session table paths
-- clickstream: $(basename "$CLICKS_TABLE")
-- orders:      $(basename "$ORDERS_TABLE")
-- inventory:   $(basename "$INVENTORY_TABLE")

-- Query 1: row counts
SELECT 'clickstream' AS tbl, COUNT(*) AS rows
FROM iceberg_scan('$CLICKS_TABLE')
UNION ALL
SELECT 'orders', COUNT(*)
FROM iceberg_scan('$ORDERS_TABLE')
UNION ALL
SELECT 'inventory', COUNT(*)
FROM iceberg_scan('$INVENTORY_TABLE');

-- Query 2: revenue by payment method
SELECT payment_method, COUNT(*) AS order_count,
    ROUND(SUM(total_amount), 2) AS total_revenue,
    ROUND(AVG(total_amount), 2) AS avg_order_value
FROM iceberg_scan('$ORDERS_TABLE')
GROUP BY payment_method
ORDER BY total_revenue DESC;

-- Query 3: clickstream → orders attribution
WITH clicks AS (
    SELECT * FROM iceberg_scan('$CLICKS_TABLE')
),
purchases AS (
    SELECT * FROM iceberg_scan('$ORDERS_TABLE')
    WHERE status = 'confirmed'
)
SELECT c.page_url,
    COUNT(DISTINCT p.order_id) AS attributed_orders,
    ROUND(SUM(p.total_amount), 2) AS attributed_revenue
FROM clicks c
JOIN purchases p ON c.user_id = p.customer_id AND c.timestamp_ms <= p.created_at_ms
GROUP BY c.page_url
ORDER BY attributed_revenue DESC
LIMIT 10;

-- Query 4: inventory snapshot
WITH latest AS (
    SELECT sku, warehouse_id, quantity_after, updated_at_ms,
        ROW_NUMBER() OVER (PARTITION BY sku, warehouse_id ORDER BY updated_at_ms DESC) AS rn
    FROM iceberg_scan('$INVENTORY_TABLE')
)
SELECT sku, warehouse_id, quantity_after AS current_stock
FROM latest WHERE rn = 1
ORDER BY current_stock ASC
LIMIT 15;

-- Query 5: unified customer view
WITH clicks AS (
    SELECT user_id, COUNT(*) AS page_views
    FROM iceberg_scan('$CLICKS_TABLE')
    GROUP BY user_id
),
purchases AS (
    SELECT customer_id AS user_id, COUNT(*) AS orders, ROUND(SUM(total_amount), 2) AS total_spent
    FROM iceberg_scan('$ORDERS_TABLE')
    GROUP BY customer_id
)
SELECT COALESCE(c.user_id, p.user_id) AS user_id,
    COALESCE(c.page_views, 0) AS page_views,
    COALESCE(p.orders, 0) AS orders,
    COALESCE(p.total_spent, 0) AS total_spent,
    CASE WHEN p.orders > 0 THEN ROUND(p.total_spent / p.orders, 2) ELSE 0 END AS avg_order_value
FROM clicks c
FULL OUTER JOIN purchases p ON c.user_id = p.user_id
ORDER BY total_spent DESC
LIMIT 15;

-- Schema evolution check: discount_code (NULL on older rows)
SELECT
  COUNT(*) AS total_orders,
  COUNT(discount_code) AS with_discount,
  COUNT(*) - COUNT(discount_code) AS null_discount
FROM iceberg_scan('$ORDERS_TABLE');

SELECT order_id, customer_id, total_amount, discount_code
FROM iceberg_scan('$ORDERS_TABLE')
ORDER BY created_at_ms DESC
LIMIT 10;
EOF

echo "Wrote $OUT"
echo "  clickstream: $(basename "$CLICKS_TABLE")"
echo "  orders:      $(basename "$ORDERS_TABLE")"
echo "  inventory:   $(basename "$INVENTORY_TABLE")"
